export const actionTypes = {
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    REGISTER_USER: "REGISTER_USER",
    ADD_TASK: "ADD_TASK",
    DELETE_TASK: "DELETE_TASK",
    MARK_TASK_COMPLETE: "MARK_TASK_COMPLETE"
};